# **Q18. Matrix Subtraction.**

In [1]:
import numpy as np

matrix1 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

matrix2 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

result = matrix1 - matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of Matrix Subtraction (Matrix1 - Matrix2):")
print(result)

Matrix 1:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result of Matrix Subtraction (Matrix1 - Matrix2):
[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]
