# **Q20. Traspose Of Matrix.**

In [1]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

transpose = matrix.T

transpose2 = np.transpose(matrix)

print("Original Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}")

print("\nTranspose Matrix (using .T):")
print(transpose)
print(f"Shape: {transpose.shape}")

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

Transpose Matrix (using .T):
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape: (3, 3)
